### PR TITLE
Day01 solution

### PR DESCRIPTION
**Pull request by RJPlog**

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx! I think your should rename your description.adoc to README.adoc for the system to pick it up.

**Comment by RJPlog** [comment]
> thanx! I think your should rename your description.adoc to README.adoc for the system to pick it up.

Hi @rdmueller, I guess I forgott to read the general README last year, but this year I did and I was puzzled by the chapter Repository structure and Documentation, because there a "description.adoc" is requested, this is why this year I did not provide a README.doc :-). I will switch to README.adoc again, sorry.

**Comment by rdmueller** [comment]
no problem. you mean there is a bug in the docs? then we should fix it!

**Comment by RJPlog** [comment]
> no problem. you mean there is a bug in the docs? then we should fix it!

@rdmueller I will change and create a pull request

**Pull request merged**
